# Local development entry points. `make dev` is the one you want.
#
# docker-compose.yml names no host port for Postgres, so Docker binds a free
# ephemeral one and a second checkout cannot collide with this one. That leaves
# the port unknown until the container exists. `make up` reads back what Docker
# assigned and writes `.env.local`, which every entry point reads in preference
# to `.env`.
#
# Docker knowledge stops here. Nothing under apps/ or packages/ knows the
# database runs in a container; they all just read DATABASE_URL.

# Fixed local development credentials, declared in docker-compose.yml. Change
# them there and here together. They are deliberately not secret; never point a
# deployed environment at them.
DB_USER := kelpie
DB_PASSWORD := kelpie
DB_NAME := kelpie_dev
TEST_DB_NAME := kelpie_test
DB_HOST := localhost

# The Compose service, and the port Postgres listens on inside the container.
DB_SERVICE := db
DB_CONTAINER_PORT := 5432

ENV_FILE := .env
LOCAL_ENV_FILE := .env.local

.DEFAULT_GOAL := help
.PHONY: help setup up down reset dev test lint typecheck build verify-packaging db-generate psql status

help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-13s\033[0m %s\n", $$1, $$2}'

setup: ## Install dependencies and create .env
	npm install
	@if [ -f $(ENV_FILE) ]; then \
		echo "$(ENV_FILE) already exists; leaving it alone"; \
	else \
		cp .env.example $(ENV_FILE); \
		node -e 'const fs=require("fs");const k=require("crypto").randomBytes(32).toString("base64");fs.writeFileSync("$(ENV_FILE)",fs.readFileSync("$(ENV_FILE)","utf8").replace(/^SECRET_ENCRYPTION_KEY=$$/m,"SECRET_ENCRYPTION_KEY="+k))'; \
		echo "created $(ENV_FILE) with a generated SECRET_ENCRYPTION_KEY"; \
	fi
	@$(MAKE) --no-print-directory up

up: ## Start Postgres and write .env.local with the port Docker assigned
	docker compose up --detach --wait $(DB_SERVICE)
	@port="$$(docker compose port $(DB_SERVICE) $(DB_CONTAINER_PORT) | head -n 1 | sed 's/.*://')"; \
	case "$$port" in \
		'' | *[!0-9]*) \
			echo "Could not read the published port of the \"$(DB_SERVICE)\" service. Try 'make down' then 'make up'." >&2; \
			exit 1 ;; \
	esac; \
	{ \
		echo "# Generated by 'make up'. Do not edit; every 'make up' overwrites it."; \
		echo "#"; \
		echo "# Docker publishes Postgres on a new port each time the container is"; \
		echo "# recreated. These override the same names in .env."; \
		echo ""; \
		echo "DATABASE_URL=postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$$port/$(DB_NAME)"; \
		echo "TEST_DATABASE_URL=postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$$port/$(TEST_DB_NAME)"; \
	} > $(LOCAL_ENV_FILE); \
	echo "db   $(DB_HOST):$$port (written to $(LOCAL_ENV_FILE))"

down: ## Stop Postgres, keeping its data
	docker compose down

reset: ## Delete the local database and start an empty one
	@printf 'This deletes the local database and everything in it. Type "yes" to continue: '; \
	read reply; \
	[ "$$reply" = yes ] || { echo "cancelled"; exit 1; }
	docker compose down --volumes
	@$(MAKE) --no-print-directory up

dev: up ## Start Postgres, then the API and the UI
	npm run dev

test: up ## Start Postgres, then run the tests
	npm test

lint: ## Run oxlint
	npm run lint

typecheck: ## Typecheck every workspace
	npm run typecheck

build: ## Build every workspace
	npm run build

verify-packaging: ## Pack the packages and check they work outside this workspace
	npm run verify:packaging

db-generate: up ## Generate migrations from the schema barrel
	npm run db:generate

psql: up ## Open a psql shell on the development database
	docker compose exec $(DB_SERVICE) psql --username $(DB_USER) --dbname $(DB_NAME)

status: ## Show the database container
	docker compose ps
