-- Hand-added, and every generated column below depends on it. Drizzle Kit does
-- not manage functions, so this line has to be maintained here.
--
-- array_to_string is STABLE rather than IMMUTABLE, because it is polymorphic over
-- anyarray and some element types have a stable output function. Postgres refuses
-- a generated column built on a stable expression. Over text[] specifically it is
-- immutable, which is what this wrapper asserts.
CREATE OR REPLACE FUNCTION kelpie_text_array_to_string(text[]) RETURNS text
  LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
  AS $$ SELECT array_to_string($1, ' ') $$;
--> statement-breakpoint
ALTER TABLE "people" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("people"."name"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("people"."email"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("people"."summary"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("people"."tags"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("companies"."name"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("companies"."domain"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("companies"."industry"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("companies"."description"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("companies"."summary"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("companies"."tags"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("companies"."tech_stack"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "positions" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("positions"."title"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A')) STORED;--> statement-breakpoint
ALTER TABLE "deals" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("deals"."name"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("deals"."risks"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("deals"."why_win"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("deals"."summary"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("deals"."tags"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("deals"."competitors"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "opportunities" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("opportunities"."name"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("opportunities"."kind"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("opportunities"."summary"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("opportunities"."tags"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "partnerships" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("partnerships"."name"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("partnerships"."kind"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("partnerships"."goals"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("partnerships"."success_looks_like"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("partnerships"."summary"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("partnerships"."tags"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "raises" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("raises"."name"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("raises"."thesis_fit"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("raises"."pass_reason"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("raises"."summary"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce(kelpie_text_array_to_string("raises"."tags"), ''), '[^[:alnum:]]+', ' ', 'g')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("roles"."title"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A')) STORED;--> statement-breakpoint
ALTER TABLE "plan_items" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("plan_items"."title"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A')) STORED;--> statement-breakpoint
ALTER TABLE "decisions" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("decisions"."body"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("decisions"."rationale"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B')) STORED;--> statement-breakpoint
ALTER TABLE "handbook_pages" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english', regexp_replace(coalesce("handbook_pages"."title"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'A') || setweight(to_tsvector('english', regexp_replace(coalesce("handbook_pages"."slug"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B') || setweight(to_tsvector('english', regexp_replace(coalesce("handbook_pages"."body"::text, ''), '[^[:alnum:]]+', ' ', 'g')), 'B')) STORED;--> statement-breakpoint
CREATE INDEX "people_search_idx" ON "people" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "companies_search_idx" ON "companies" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "positions_search_idx" ON "positions" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "deals_search_idx" ON "deals" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "opportunities_search_idx" ON "opportunities" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "partnerships_search_idx" ON "partnerships" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "raises_search_idx" ON "raises" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "roles_search_idx" ON "roles" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "plan_items_search_idx" ON "plan_items" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "decisions_search_idx" ON "decisions" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "handbook_pages_search_idx" ON "handbook_pages" USING gin ("search_vector");